---
abstract: 'Output progress to terminal as color bar'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Progress-Any-Output-TermProgressBarColor
recommends:
  Term::Size: 0
requires:
  Color::ANSI::Util: 0
  Progress::Any: 0.10
  Text::ANSI::Util: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Progress-Any-Output-TermProgressBarColor
  repository: http://github.com/sharyanto/perl-Progress-Any-Output-TermProgressBarColor
version: 0.07
